# Define how to group processes in the analysis

# cat colors: https://cms-analysis.docs.cern.ch/guidelines/plotting/colors/#categorical-data-eg-1d-stackplots
# These colors are defined under py

# Special label

ttg_split:

  - name: TTG_fromProd
    procs: [ TTG_fromProd ]
    stack: True
    histo-decorations: 
      SetFillColor: light_blue
      SetLineWidth: 0
    label: 'tt#gamma (prod.)'

  - name: TTG_fromDecay
    procs: [ TTG_fromDecay ]
    stack: True
    histo-decorations:
      SetFillColor: blue 
      SetLineWidth: 0
    label: 'tt#gamma (decay)'

  - name: TTG_fromDec_eft
    procs: [ TTG_fromDec_eft ]
    stack: False
    histo-decorations:
      SetFillColor: empty
      SetLineColor: orange 
      SetLineWidth: 2
    label: 'tt#gamma (decay - SM)'

  - name: TTG_fromProd_eft
    procs: [ TTG_fromProd_eft ]
    stack: False
    histo-decorations:
      SetFillColor: empty 
      SetLineColor: dark_orange
      SetLineWidth: 2
    label: 'tt#gamma (prod. - SM)'
