procname: TTGamma-1Jets-TTto2L2Nu_xcut20-qcut42

# ------ Configurations regarding the Matrix Element
load_extramodels: dim6top_LO_UFO.tar.gz 
model: 'dim6top_LO_UFO-restrict_ttg'
process: [
    'define p = g u c d s u~ c~ d~ s~ b b~',
    'define j = p',
    'define l+ = e+ mu+ ta+',
    'define l- = e- mu- ta-',
    'define vl = ve vm vt',
    'define vl~ = ve~ vm~ vt~',
    'generate p p > t t~ a FCNC=0 DIM6=1, (t > l+ vl b FCNC=0 DIM6=0), (t~ > l- vl~ b~ FCNC=0 DIM6=0) @0 ', 
    'add process p p > t t~ a j FCNC=0 DIM6=1, (t > l+ vl b FCNC=0 DIM6=0), (t~ > l- vl~ b~ FCNC=0 DIM6=0) @0 ', 
  ]

template_run_card: 
  name: templates/template_run_card_LO.dat 

template_customizecards: 
  name: templates/template_customizecards.dat
  extraopts: [
    "set param_card DECAY 6 1.491500e+00", # This is to mimic what was done in the central sample
    "set run_card ptj 20",
    "set run_card xqcut 20",
    "set run_card maxjetflavor 5"
  ] 

template_restrict_card: 
  name: templates/template_restrict_ckm_no_b_mass.dat 
  restrict_name: restrict_ttg

# ------ Configurations regarding the Parton shower
fragment:
  name: templates/template_partonshower_madgraphMLM.dat
  process_parameters: [
    "'JetMatching:qCut = 42.'",
    "'JetMatching:qCutME = 20.'",
    "'JetMatching:nQmatch = 5'",
    "'JetMatching:nJetMax = 1'",
    "'TimeShower:mMaxGamma = 4.0'"
  ]
