# Essentially Table 6 of https://arxiv.org/pdf/1802.07237
# ---------------------------
# Using same notation for groupings as TOP-22-006.

4hq: 
  # Color singlets
  - [cQQ1, -1.0, 1.0] # Combination of SU(2) singlet + triplet. Unbroken phase. 
  - [cQt1, -1.0, 1.0] 
  - [cQb1, -1.0, 1.0] 
  - [ctt1, -1.0, 1.0]  
  - [ctb1, -1.0, 1.0] 
  - [cQtQb1, -1.0, 1.0] # CP even
  - [cQtQb1I, -1.0, 1.0] # CP odd

  # Color octets
  - [cQQ8, -1.0, 1.0] # Sensitive to SU(2) triplet. Unbroken phase. 
  - [cQt8, -1.0, 1.0] 
  - [cQb8, -1.0, 1.0]
  - [ctb8, -1.0, 1.0] 
  - [cQtQb8, -1.0, 1.0] # CP even
  - [cQtQb8I, -1.0, 1.0] # CP odd

2hq2lq:
  # LL->LL
  # Color singlets
  - [cQq11, -1.0, 1.0] 
  - [cQq13, -1.0, 1.0] 
  # Color octets
  - [cQq81, -1.0, 1.0]
  - [cQq83, -1.0, 1.0]
  
  # RR->RR  
  - [ctq1,  -1.0, 1.0]
  - [ctq8, -1.0, 1.0]
  - [ctu1,  -1.0, 1.0]
  - [ctu8,  -1.0, 1.0]
  - [ctd1,  -1.0, 1.0]
  - [ctd8,  -1.0, 1.0]

  # LL->RR
  # Color singlets
  - [cQu1,  -1.0, 1.0]
  - [cQd1,  -1.0, 1.0]
  # Color octets
  - [cQu8, -1.0, 1.0]
  - [cQd8,  -1.0, 1.0]

# Two heavy operators
2hqV:
  # t-H  
  - [ctp,  -1.0, 1.0]
  - [ctpI, -1.0, 1.0]

  # Effective shifts to t-Z, t-W
  # Covariant derivatives + SU(2) doublets
  - [cpQM, -1.0, 1.0] 
  - [cpQ3, -1.0, 1.0] 
  
  # Covariant derivatives + SU(2) singlets - up type
  - [cptb, -1.0, 1.0] 
  - [cptbI, -1.0, 1.0] 

  # These operators connect doublets to singlets  
  - [ctW,  -1.0, 1.0]
  - [ctWI, -1.0, 1.0]
  - [ctZ,  -1.0, 1.0]
  - [ctZI, -1.0, 1.0]
  - [ctG, -1.0, 1.0]
  - [ctGI, -1.0, 1.0]
  - [cbW, -1.0, 1.0] 
  - [cbWI, -1.0, 1.0] 

2hq2l:
  - [cQlM1, -1.0, 1.0] 
  - [cQlM2, -1.0, 1.0] 
  - [cQlM3, -1.0, 1.0] 
  - [cQl31, -1.0, 1.0] 
  - [cQl32, -1.0, 1.0] 
  - [cQl33, -1.0, 1.0] 
  - [ctl1, -1.0, 1.0]
  - [ctl2, -1.0, 1.0]
  - [ctl3, -1.0, 1.0]
  - [cte1, -1.0, 1.0]
  - [cte2, -1.0, 1.0]
  - [cte3, -1.0, 1.0]
  - [ctlS1, -1.0, 1.0]  
  - [ctlS2, -1.0, 1.0] 
  - [ctlS3, -1.0, 1.0] 
  - [ctlSI1, -1.0, 1.0] 
  - [ctlSI2, -1.0, 1.0] 
  - [ctlSI3, -1.0, 1.0]   
  - [ctlT1, -1.0, 1.0]
  - [ctlT2, -1.0, 1.0]
  - [ctlT3, -1.0, 1.0]
  - [ctlTI1, -1.0, 1.0] 
  - [ctlTI2, -1.0, 1.0] 
  - [ctlTI3, -1.0, 1.0]
  - [cQe1, -1.0, 1.0] 
  - [cQe2, -1.0, 1.0] 
  - [cQe3, -1.0, 1.0] 
