analysis_name: 
  TTG_TOP-23-002

samples:
  - procname: TTG_GammaFromProd_1Jets_SMEFT_dim6top_LO
    # ------ Configurations regarding the Matrix Element
    model: 'dim6top_LO_UFO'
    process: [
        'define p = g u c d s u~ c~ d~ s~ b b~',
        'define j = p',
        'define l+ = e+ mu+ ta+',
        'define l- = e- mu- ta-',
        'define vl = ve vm vt',
        'define vl~ = ve~ vm~ vt~',
        'generate p p > t t~ a FCNC=0 DIM6=1, (t > l+ vl b FCNC=0 DIM6=0), (t~ > l- vl~ b~ FCNC=0 DIM6=0) @0 ', 
        'add process p p > t t~ a j FCNC=0 DIM6=1, (t > l+ vl b FCNC=0 DIM6=0), (t~ > l- vl~ b~ FCNC=0 DIM6=0) @0 ', 
      ]

    template_run_card: 
      name: templates/template_run_card_LO.dat 

    template_customizecards: 
      name: templates/template_customizecards.dat
      extraopts: [
        "set run_card ptj 20",
        "set run_card xqcut 20",
        "set run_card maxjetflavor 5"
      ] 

    # ------ Configurations regarding the Parton shower
    fragment:
      name: templates/template_partonshower_madgraphMLM.dat
      process_parameters: [
        "'JetMatching:qCut = 42.'",
        "'JetMatching:qCutME = 20.'",
        "'JetMatching:nQmatch = 5'",
        "'JetMatching:nJetMax = 1'",
        "'TimeShower:mMaxGamma = 4.0'"
      ]

analysis:
  samples: 
    TTG_from_prod: 
      path: /eos/cms/store/group/phys_top/cvicovil/top-comb/nanogen/TTG_GammaFromProd_1Jets_SMEFT_dim6top_LO
      files: batch_12_08_2025_1743/genfiles/*root
      xsec: 1.0 # change
  plugins: [
    plugins/TTG_TOP-23-002.cc
  ]
  definitions: definitions.TTG_TOP-23-002
  plots: definitions.TTG_TOP-23-002
  outpath: outplots/TTG_TOP-23-002

# The syntax is:
# [operator_name, reference_point, minBound, maxBound ]
operators:
  scans:
      - [ctG, 1.0, -1.0, 1.0]
      - [ctGI, 1.0, -1.0, 1.0]
      - [ctp,  1.0, -1.0, 1.0]
      - [ctpI, 1.0, -1.0, 1.0]
      - [ctW, 1.0, -1.0, 1.0]
      - [ctWI, 1.0, -1.0, 1.0]
      - [ctZ, 1.0, -1.0, 1.0]
      - [ctZI, 1.0, -1.0, 1.0]
  algo: one_by_one-two_by_two


