analysis_name: 
  TTG_TOP-23-002

samples: 
  files: [ 
    configs/ttgamma/TTGamma-1Jets-TTto2L2Nu_xqcut20_qCut42.yml, # From production 
    configs/ttgamma/TT-1Jets-TTto2L2NuGamma_xqcut20_qCut42.yml # From decay
  ]

operators: 
  files: [ configs/list_operators.yml ]
  groups: [
    4hq,
    #2hq2lq,
    #2hqV,  
    #2hq2l # --- Sensitivity to these comes mainly from single top scattering with b quarks or ttW
  ]
  mask: []
  algo: one_by_one

analyses:
  definitions: definitions.TTG_TOP-23-002
  plots: definitions.TTG_TOP-23-002
  PhotonCategorization:
    config: configs/ttgamma/validate_photon_categories.yml 
    norm: ~ 
    draw: stack
    sel-plots: [ genphoton_categories ]
    plot-only: [] 

  FiducialSelectionValidation:
    config: configs/ttgamma/fiducial_selection_validation.yml 
    norm: integral 
    draw: ~ # This defaults to overline
    sel-plots: [ leading_genphoton_pt ]
    plot-only: [] 
