analysis_name: 
  ttgamma

# Define the aspects regarding the generation of MC: gridpacks and operators
generation:
  samples:
    - configs/ttgamma/TTGamma-1Jets-TTto2L2Nu_xqcut20_qCut42.yml 
    - configs/ttgamma/TT-1Jets-TTto2L2NuGamma_xqcut20_qCut42.yml
  operators:
    files: [ configs/list_operators.yml ]
    groups: [ ]
    mask: [ cptbI, ctWI, ctZI, ctGI, cbWI, ctpI ]
    algo: one_by_one-two_by_two

 
reinterpretation:
  datasets: configs/ttgamma/datasets.yml
  hooks: configs/ttgamma/hooks.py
  definitions: configs/ttgamma/definitions.py
     
  # ---- Load auxiliar .cpp code used to build custom variables
  plugins: 
    - plugins/common_functions.cc
    - plugins/TTG_TOP-23-002.cc
  
  # ---- Steps to build the analysis
  sequence: configs/ttgamma/main_analysis_sequence.yml 

  # ---- These determine event level selections and corrections
  flows: configs/ttgamma/flows.yml



  plotting:
    outpath: /eos/user/c/cvicovil/www/top-comb/
    file: configs.ttgamma.plots_partonLevel
    groupings: configs/ttgamma/groupings.yml
    splitting: ttg_split 
 
